### PR TITLE
E2E decreased test and waitFor Timeouts

### PR DESCRIPTION
**Pull request by stefancplace**

### CODE REVIEW

**Review by qa-joerg — APPROVED** [review]
Will this force problems `callTestSetupHandler` or loading cplace?

**Comment by stefancplace** [comment]
> callTestSetupHandler

yes can cause problems, as discussed yesterday you can work around by increasing timeout specifically for a testcase
`        before(function () {
            browser.setWindowSize(1680, 1050);
            this.timeout(60_000)
            callTestSetupHandler('/test/TestSetupSchedulesWithPGProfile');
            navigateToTaskPage(pages.homePage.textPageFromHomePage(3));
        });
`

**Comment by stophi-dev** [comment]
So why do we exactly want to reduce the timeouts?

**Comment by stefancplace** [comment]
I think the argument in yesterdays discussion was to reduce the overall time the tests need to run.
E.g. why wait 60 seconds when it`s already clear that a test has failed

**Comment by stefancplace** [comment]
Yet decreasing timeouts might cause further problems....
a good description of timeouts in wdio can be found here 
https://webdriver.io/docs/timeouts.html#:~:text=WaitFor*%20timeout,element%20to%20reach%20the%20state.

**Review by stophi-dev — APPROVED** [review]
Ok, as discussed on Slack:
we can reduce the timeouts and if it causes too much problems, we could change them again.

**Pull request merged**
