### PR TITLE
Add support for WebdriverIO v6

### PR DESCRIPTION
**Pull request by rose-m**

### CODE REVIEW

**Comment by stefancplace** [comment]
I checked locally, not sure if I missed something but it seems libs from another plugin cant not yet be resolved.

image

**Comment by rose-m** [comment]
@stefancplace Thanks - finally found it! can you test again?

**Review by stefancplace — APPROVED** [review]
thanks, nice  👍
didnt test from another repo e.g. project-planning, the import mechanism should be the same though

**Comment by rose-m** [comment]
@stophi-dev Maybe you just want to test-drive that version if it works fine on your windows machine? Not especially regarding WDIO 6 but just with the regular master branch in project planning...

**Review by stophi-dev — COMMENTED** [review]
Please don't merge yet.
I had some problems with the assets compiler:
```
../main/node_modules/@jest/types/build/Config.d.ts:10:15 - error TS2614: Module '"../../../chalk/types"' has no exported member 'ForegroundColor'.
Did you mean to use 'import ForegroundColor from "../../../chalk/types"' instead?
```
I am investigating this now.

**Comment by stefancplace** [comment]
was thinking about it, actually wdio v5 should work with the changes introduced for v6. Maybe we dont need the differentiation at all...

**Comment by qa-joerg** [comment]
Running e2e tests on project-planning leeds into this error

**Comment by rose-m** [comment]
@stefancplace I tried - the changes don't work properly with v5... or I made a mistake while trying :D

**Comment by rose-m** [comment]
@stophi-dev Did you for sure have the latest version of the branch in `main` with a proper package.json and package-lock.json?

**Comment by stefancplace** [comment]
I just switched this line:
`        if (webdriverioVersion.match(/^.?5(\..+)?/)) {
            return 'v6';
        } else if (webdriverioVersion.match(/^.?6(\..+)?/)) {
            return 'v6';
`
and run it on cplace/master -> starts fine
had to remove node_modules and do npm install to get wdio v5 again
Also possible I missed something...

**Comment by rose-m** [comment]
Alright will check again

**Comment by stophi-dev** [comment]
I tested with the branch `e2e/ISSUE-4467-Update-WebdriverIO-to-6` and also tried to merge latest `master` in main.
It should work with that branch, right?

**Comment by rose-m** [comment]
I removed the differentiation between the versions - it now works with one template for all webdriver versions.

**Comment by stefancplace** [comment]
nice thanks, I guess we have to update tsconfig.base.e2e.json in main for all branches >4.57 ?

**Comment by qa-joerg** [comment]
compiler works on main an project-planning

**Comment by stefancplace** [comment]
Works fine on WDIO v6 in platform for:
`cplace-cli e2e --plugins cf.cplace.landingPageFromPage``
and 
`cplace-cli e2e --plugins cf.cplace.platform --specs="**/login.spec.ts"``

the same tests show an error on WDIO v5 (master branch), actually the tests run fine but on shutdown there is an error:
image

**Comment by qa-joerg** [comment]
Also all project-planning tests are running like they used to. I need to check board now

**Review by stophi-dev — CHANGES_REQUESTED** [review]
I have compatibility issues with this cplace-cli branch and the current `master` (WebdriverIO v5) in the cplace repository.

`cplace-cli e2e --headless --specs '**/login.spec.ts'`
ERROR @wdio/local-runner: Failed launching test session: TypeError: args[0].endsWith is not a function

**Comment by rose-m** [comment]
I'm still investigating @stophi-dev but not found a solution yet...

**Review by stophi-dev — APPROVED** [review]
It works now with Webdriver 5 and Webdriver 6 on my machine.

**Review by stefancplace — APPROVED** [review]
works on my machine as well, thanks for consolidating the versions

**Comment by rose-m** [comment]
Then I'll merge it and create a new version :)

**Pull request merged**
