### PR TITLE
PFM-ISSUE-12530: cplace-cli: fix vulnerabilities

### PR DESCRIPTION
**Pull request by Kaltenbach**
Resolves [PFM-ISSUE-12530](https://base.cplace.io/pages/38zfihl0l9ks8luogxvox5g8t/PFM-ISSUE-12530-cplace-cli-fix-vulnerabilities)

### CODE REVIEW

**Comment by Kaltenbach** [comment]
Needs integration tests.

**Comment by Benno42** [comment]
The test` H) A tag that does not exist is configured`  failed  in the` UpdateRepos.test.ts`. 
On my computer also failed  `A) only branches are configured and there are no remote tag`.

**Comment by Benno42** [comment]
I tested the following parts of the cplace-cli:
✅ release-notes --from
✅repos --clone 
✅repos --update
✅repos --write --freeze --latest-tag
✅repos merge-skeleton
✅repos --validateBranches
❌ repos --branch test-branch -> I get an error.
### steps to reproduce:

1. clone cplace-oidc
2. `cd cplace-odic`
3. `cplace-cli repos --clone`
4. `cplace-cli repos --branch test-branch`
I get an error message:
```
Parent repo is main
Failed to update repo description Error: ENOENT: no such file or directory, open '/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/test/main/parent-repos.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at BranchRepos.adjustParentReposJsonAndCommit (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/dist/commands/repos/BranchRepos.js:78:44)
    at findRepos.map.map.map.concurrency (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/dist/commands/repos/BranchRepos.js:45:33)
    at tryCatcher (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray._drainQueue (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/map.js:122:14)
    at M

```

When I follow the same steps with cplace-cli version 1.0.9 everything works fine.

**Comment by Kaltenbach** [comment]
> 3\. ``
> 4\. `cplace-cli repos --branch test-branch`
>     I get an error message:
> 
> ```
> Parent repo is main
> Failed to update repo description Error: ENOENT: no such file or directory, open '/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/test/main/parent-repos.json'
>     at Object.openSync (node:fs:603:3)
>     at Object.readFileSync (node:fs:471:35)
>     at BranchRepos.adjustParentReposJsonAndCommit (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/dist/commands/repos/BranchRepos.js:78:44)
>     at findRepos.map.map.map.concurrency (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/dist/commands/repos/BranchRepos.js:45:33)
>     at tryCatcher (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/util.js:16:23)
>     at MappingPromiseArray._promiseFulfilled (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/map.js:68:38)
>     at MappingPromiseArray._drainQueue (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/map.js:122:14)
>     at M
> ```
> 
> When I follow the same steps with cplace-cli version 1.0.9 everything works fine.

I'll check but possibly the test setup ishould be with a repo that has parents? 🤔 cplace main never had a parent-repos.json...

**Comment by Kaltenbach** [comment]
> > 3. ``
> > 4. `cplace-cli repos --branch test-branch`
> > I get an error message:
> > ```
> > Parent repo is main
> > Failed to update repo description Error: ENOENT: no such file or directory, open '/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/test/main/parent-repos.json'
> >     at Object.openSync (node:fs:603:3)
> >     at Object.readFileSync (node:fs:471:35)
> >     at BranchRepos.adjustParentReposJsonAndCommit (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/dist/commands/repos/BranchRepos.js:78:44)
> >     at findRepos.map.map.map.concurrency (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/dist/commands/repos/BranchRepos.js:45:33)
> >     at tryCatcher (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/util.js:16:23)
> >     at MappingPromiseArray._promiseFulfilled (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/map.js:68:38)
> >     at MappingPromiseArray._drainQueue (/Users/heikobensch/cplace-dev/repos-review/PFM-ISSUE-12530/cplace-npm-tools/node_modules/bluebird/js/release/map.js:122:14)
> >     at M
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I follow the same steps with cplace-cli version 1.0.9 everything works fine.
> 
> I'll check but possibly the test setup should be with a repo that has parents? 🤔 cplace main never had a parent-repos.json...
> 
> ... but I wonder why that even worked before. The file did not change and there has been no check if the file exists...

There was a file check by path comparison. With the update of simple-git, the base path property of simple-git is not accessible any more and hence the cplace-cli method returning the base path changed, using an absolute path. With that, the check failed in the BranchRepos command.

**Review by Benno42 — APPROVED** [review]
🚀 LGTM and  works as expected.

**Comment by Kaltenbach** [comment]
Integration tests will be done together with [PFM-ISSUE-27294](https://base.cplace.io/pages/h51v5geqi7bkhlu4w0uel72v3/PFM-ISSUE-27294-cplace-cli-don-t-throw-an-error-when-freezing-the-parent-repos)

**Pull request merged**
