### PR TITLE
PFM-ISSUE-4620 Shorten the name of e2e screenshot

### PR DESCRIPTION
**Pull request by rishoocplace**
replacing the screenshot name from `test.fullTitle` to `test.title`

### CODE REVIEW

**Comment by stefancplace** [comment]
Did you test the changes locally?

**Comment by rishoocplace** [comment]
> Did you test the changes locally?

Yup i did seem to work fine.
image

**Comment by stefancplace** [comment]
Thanks a lot for your effort @rishoocplace

**Comment by stefancplace** [comment]
Resolves [PFM-ISSUE-4620](https://base.cplace.io/pages/s77wfvp5hkupyxxbcx8jeqytc/ISSUE-4620-shorten-the-name-of-e2e-screenshots-on-jenkins#id_ryv8bgmhbp5kptlna9mpurvyu=Layout_AppsTeam_Issue_intro)

`changelog: cplace-cli: [PFM-ISSUE-4620]  Shorten the name of e2e screenshot  [PR cplace#56]`

**Pull request merged**
