### PR TITLE
removing {w3c: false} from 'goog:chromeOptions' in WdioConfigTemplate.ts

### PR DESCRIPTION
**Pull request by qa-joerg**

### CODE REVIEW

**Comment by qa-joerg** [comment]
We add `w3c: false` to the wdioConfig with the webdriver io update last year. 
```
'goog:chromeOptions': {
                    w3c: false,
                    args: [
                        '--headless',
                        '--disable-gpu',
                        '--disable-dev-shm-usage',
                        '--no-sandbox',
                    ]
                }
```
This was a workaround because we had problems with mocha. Now the problem is back so we need to remove this again.

**Review by stefancplace — DISMISSED** [review]
LGTM

**Comment by stefancplace** [comment]
Could you give a description on the error that you want to solve with this PR?

**Comment by qa-joerg** [comment]
This won't fix this issue we have 
```
@wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "mocha" framework, neither as wdio scoped package "@wdio/mocha-framework" nor as community package "wdio-mocha-framework". Please make sure you have it installed!
    at initialisePlugin (/usr/local/lib/node_modules/@wdio/local-runner/node_modules/@wdio/utils/build/initialisePlugin.js:32:9)
    at Runner.run (/usr/local/lib/node_modules/@wdio/local-runner/node_modules/@wdio/runner/build/index.js:75:50)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
/Users/joergstoeger/CPlace/repos/main/node_modules/@wdio/cli/build/interface.js:127
            throw new Error('Could not find job');
            ^
```
Looks like a local individuell problem

**Pull request closed without merging**
