### PR TITLE
PFM-ISSUE-7248: Shallow Clones for Parent Repos

### PR DESCRIPTION
**Pull request by Kaltenbach**
Resolves [PFM-ISSUE-7248](https://base.cplace.io/pages/wpslc6iselmpuidba6qon4kf2/PFM-ISSUE-7248-Shallow-Clones-for-Parent-Repos)

Manual test report and measures are found in the PFM issue.

### CODE REVIEW

**Comment by Kaltenbach** [comment]
I'm not sure about how versioning is handled here, @stefancplace and @stophi-dev . For a first try (also to test the build locally) I changed the version to `0.19.11-dev`. This should be changed before merging I guess.

**Comment by stophi-dev** [comment]
Creating a release is described here:
https://github.com/collaborationFactory/cplace-npm-tools#publishing-a-new-version

**Comment by Kaltenbach** [comment]
Thank you @stophi-dev 😄 Funny I haven't seen this 🙈

**Review by stophi-dev — COMMENTED** [review]
Just have a minor remark with invalid values. I didn't test it, though.

Regarding the use cases, I am not sure when we need this exactly. 
For circleci, I think we have the git directory cashed, so it will not create new clones from scratch.
As a developer, I'd maybe prefer to have the `--filter=blob:none` or `--filter=blob:limit=1m` options rather than having a shallow clone. Then I have full access to the history, but it would fetch blobs only on demand, which should reduce the repo size and initial cloning time also significantly.

**Review by stophi-dev — APPROVED** [review]

**Comment by Kaltenbach** [comment]
> Regarding the use cases
Considering CircleCi: we want to get rid of the caches as they need to be defined explicitly for each parent repo in every build what keeps us from moving to a generic configuration here. Shallow clones allow us to do so.

Other partner developers also asked us to implement shallow cloning as they have slow internet connections (behind company proxy) and need this for their custom build environments. This would also possibly speed up builds of the IDP

**Comment by stefancplace** [comment]
Definitely a great features :)

**Pull request merged**
